- name: ANSIBLE_CENTOS_BASE | BASHPROFILE | root user
  copy:
    src: bash_profile
    dest: "/root/.bash_profile"
    owner: root
    group: root
    mode: 0644

- name: ANSIBLE_CENTOS_BASE | BASHPROFILE | "{{ ansible_centos_base__username }}" user
  copy:
    src: bash_profile
    dest: "/home/{{ ansible_centos_base__username }}/.bash_profile"
    owner: "{{ ansible_centos_base__username }}"
    group: "{{ ansible_centos_base__username }}"
    mode: 0644
