---
- name: ANSIBLE_CENTOS_BASE | FIREWALL | Ensure iptables is not running
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - iptables
    - ip6tables
  ignore_errors: yes

- name: ANSIBLE_CENTOS_BASE | FIREWALL | Install firewalld
  yum:
    name: firewalld
    state: present

- name: ANSIBLE_CENTOS_BASE | FIREWALL | Ensure firewalld is started and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: yes

- name: ANSIBLE_CENTOS_BASE | FIREWALL | Block timestamp-request and timestamp-reply
  firewalld:
    icmp_block: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - timestamp-request
    - timestamp-reply
