---
- name: ANSIBLE_CENTOS_BASE | KERNEL | Disable various kernel modules
  copy:
    content: "install {{ item }} /bin/false"
    dest: /etc/modprobe.d/{{ item }}.conf
  loop: "{{ ansible_centos_base__modules_to_disable }}"
