---
- name: ANSIBLE_CENTOS_BASE | SERVICES | Do not allow normal users to use cron
  copy:
    content: "root"
    dest: "/etc/cron.allow"
    owner: root
    group: root
    mode: 0644

- name: ANSIBLE_CENTOS_BASE | SERVICES | Disable mail services
  service:
    name: "{{ item }}"
    enabled: false
  register: systemd_output
  failed_when: "systemd_output.failed == 1 and ('Could not find the requested service' not in systemd_output.msg)"
  loop:
    - "exim4"
    - "postfix"
