---
- name: ANSIBLE_CENTOS_BASE | SSHD | Create the file /etc/ssh/banner
  copy:
    content: |
      *  Toda sua atividade pode ser rastreada atraves de logs.
      *  Opere este sistema com cuidado.
    dest: /etc/ssh/banner

# V-38613 - The ssh daemon must not permit root logins
- name: ANSIBLE_CENTOS_BASE | SSHD | root login | Set the config PermitRootLogin to "yes"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?PermitRootLogin"
    line: "PermitRootLogin yes"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  when: ansible_centos_base__root_login is defined and ansible_centos_base__root_login == "yes"

# V-38613 - The ssh daemon must not permit root logins
- name: ANSIBLE_CENTOS_BASE | SSHD | root login | Set the config PermitRootLogin to "no"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(#)?PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  when: ansible_centos_base__root_login is defined and ansible_centos_base__root_login == "no"

- name: ANSIBLE_CENTOS_BASE | SSHD | Setup sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.reg }}"
    line: "{{ item.line }}"
    state: present
    validate: '/usr/sbin/sshd -T -f %s'
  loop: "{{ ansible_centos_base__sshd_configuration }}"
  notify: restart_ssh
