- name: HARDENING | LOGINTIMEOUT | Apply login auto timeout policy
  copy:
    src:  profile.d--login-timeout.sh
    dest: /etc/profile.d/login-timeout.sh
    owner: root
    group: root
    mode: 0644
