---
- name: ANSIBLE_CENTOS_BASE | PACKAGES | Ensure EPEL installed
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Ensure deltarpm installed
  yum:
    name: drpm
    state: present
  when: ansible_distribution_major_version >= '8'

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Ensure deltarpm installed
  yum:
    name: deltarpm
    state: present
  when: ansible_distribution_major_version <= '7'

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Ensure basic packages installed
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ ansible_centos_base__packages_centos8 }}"
  when: ansible_distribution_major_version >= '8'

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Ensure basic packages installed
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ ansible_centos_base__packages_centos7 }}"
  when: ansible_distribution_major_version <= '7'

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Install Extra packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ ansible_centos_base__packages_extra }}"
  when: ansible_centos_base__packages_extra is defined
  notify:
    - restart crond

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Upgrade any out of date packages
  yum:
    name: '*'
    state: latest # noqa 403
    update_cache: yes

- name: ANSIBLE_CENTOS_BASE | PACKAGES | Install pexpect via pip
  pip:
    name: "pexpect"
    version: "3.3"
