---
 - name: restart_ssh
   service:
     name: sshd
     state: restarted

 - name: start auditd
   service:
    name: auditd
    state: started
   when: ansible_virtualization_type != "docker"

 - name: restart crond
   service:
     name: crond
     state: restarted
